"""empty message

Revision ID: 088d81ffef3a
Revises: d34f538b4c3b
Create Date: 2025-01-08 11:48:01.719575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '088d81ffef3a'
down_revision = 'd34f538b4c3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_post_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_timestamp'))
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
